server:
  port: 9999
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: learning-spring-boot-comments
          group: comments-service
          content-type: application/json
  
spring:
  data:
    mongodb:
      uri: mongodb://alin:alin@ds037005.mlab.com:37005/mongolab_alin
